"""No-GPU V2B Slim frontier, diagnostic, and evidence-selector audit.

The policies are declared below before any gold labels are inspected.  Gold is
only read by ``gold_diagnostics`` after the inference-only worklists have been
materialised in memory.  This script never loads a model, invokes Beam, or
writes a submission.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import Counter, defaultdict
from pathlib import Path
from statistics import median
from typing import Any, Callable

from analyze_post_k500_bounded_union_v2 import RECOVERY, doc_features, index, load_jsonl, rrf


ROOT = Path(__file__).resolve().parents[2]
CHUNKS = ROOT / "data/processed_v3/chunks"
K500_COST = 487_914


def percentile(values: list[int | float], q: float) -> int | float | None:
    if not values:
        return None
    return sorted(values)[max(0, math.ceil(len(values) * q) - 1)]


def distribution(values: list[int | float]) -> dict[str, Any]:
    return {
        "count": len(values),
        "mean": sum(values) / len(values) if values else None,
        "median": median(values) if values else None,
        "p95": percentile(values, 0.95),
        "min": min(values) if values else None,
        "max": max(values) if values else None,
    }


def words(text: str) -> set[str]:
    return {token for token in text.lower().split() if len(token) > 1}


def selector_chunks(qwords: set[str], chunks: list[dict[str, Any]], topk: int = 3) -> list[str]:
    ranked = sorted(
        chunks,
        key=lambda row: (-len(qwords & words(str(row.get("text", "")))), str(row.get("chunk_id", ""))),
    )
    return [str(row["chunk_id"]) for row in ranked[:topk] if str(row.get("text", "")).strip()]


def load_rankings() -> tuple[dict[str, dict[str, Any]], dict[str, dict[str, Any]], dict[str, dict[str, Any]], dict[str, dict[str, list[str]]]]:
    baseline = index(load_jsonl(RECOVERY / "baseline_093_oof/predictions.jsonl"))
    decisions = index(load_jsonl(RECOVERY / "adaptive_k500_v1/adaptive_k500_decisions.jsonl"))
    k200 = index(
        load_jsonl(RECOVERY / "baseline_093_oof/sources/fold0_original_bge_chunk200_compact.jsonl")
        + load_jsonl(RECOVERY / "baseline_093_oof/sources/f1to4_original_bge_chunk200_compact.jsonl")
    )
    k500 = index(load_jsonl(RECOVERY / "selective_bge_k500_v1_from_beam/new_chunk_scores.jsonl"))
    lexical: dict[str, dict[str, list[str]]] = {name: {} for name in ("bm25", "knn_word", "knn_char")}
    checkpoint = RECOVERY / "candidate_union_ablations/checkpointed_lexical_v1/checkpoints"
    for name in lexical:
        for fold in range(5):
            payload = json.loads((checkpoint / f"{name}_fold{fold}.json").read_text(encoding="utf-8"))
            lexical[name].update({str(qid): [str(doc) for doc in docs] for qid, docs in payload["rankings"].items()})
    expected = set(baseline)
    if any(set(mapping) != expected for mapping in (decisions, k200, *lexical.values())):
        raise ValueError("cache coverage mismatch")
    return baseline, decisions, k200, k500, lexical


def checkpoint_chunk_counts() -> dict[tuple[str, str], int]:
    """Read only compact checkpoint metadata already generated by full preflight."""
    state = RECOVERY / "selective_bge_bounded_union_v2b_preflight/checkpoints"
    counts: dict[tuple[str, str], int] = {}
    for path in sorted(state.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        for row in payload.get("rows", []):
            key = (str(row["query_id"]), str(row["doc_id"]))
            counts[key] = counts.get(key, 0) + 1
    if not counts:
        raise FileNotFoundError("full V2B preflight checkpoints are required")
    return counts


def build_candidates(
    baseline: dict[str, dict[str, Any]], decisions: dict[str, dict[str, Any]],
    k200: dict[str, dict[str, Any]], k500: dict[str, dict[str, Any]],
    lexical: dict[str, dict[str, list[str]]],
) -> tuple[list[dict[str, Any]], dict[str, set[str]]]:
    rows: list[dict[str, Any]] = []
    existing: dict[str, set[str]] = {}
    for qid, base in baseline.items():
        adaptive = [str(doc) for doc in decisions[qid]["k200_documents"]] + [str(doc) for doc in decisions[qid]["k500_added_documents"]]
        sources = {"adaptive": adaptive, "bm25": lexical["bm25"][qid], "knn_word": lexical["knn_word"][qid], "knn_char": lexical["knn_char"][qid]}
        known = set(doc_features(k200[qid]["hits"])) | (set(doc_features(k500[qid]["new_hits"])) if qid in k500 else set())
        existing[qid] = known
        union = rrf(list(sources.values()))[:200]
        ranks = {name: {doc: rank for rank, doc in enumerate(docs, 1)} for name, docs in sources.items()}
        for union_rank, doc in enumerate(union, 1):
            if doc in known:
                continue
            membership = [name for name, rank_map in ranks.items() if doc in rank_map]
            rows.append({
                "query_id": qid, "doc_id": doc, "fold": int(base["fold"]), "union_rank": union_rank,
                "source_support": len(membership), "sources": membership,
                "bm25_rank": ranks["bm25"].get(doc), "knn_support": int(doc in ranks["knn_word"]) + int(doc in ranks["knn_char"]),
            })
    return rows, existing


def policy_definitions() -> list[tuple[str, Callable[[dict[str, Any]], bool]]]:
    policies: list[tuple[str, Callable[[dict[str, Any]], bool]]] = []
    for cap in (25, 50, 100, 150, 200):
        policies.append((f"union_rank_le_{cap}", lambda row, cap=cap: row["union_rank"] <= cap))
    # Per-query caps are applied after the missing candidates have been ordered by locked union rank.
    for cap in (10, 20, 40, 80):
        policies.append((f"per_query_missing_top_{cap}", lambda row: True))
    policies.extend([
        ("multi_source_support_ge_2", lambda row: row["source_support"] >= 2),
        ("bm25_rank_le_20", lambda row: row["bm25_rank"] is not None and row["bm25_rank"] <= 20),
        ("bm25_rank_le_50", lambda row: row["bm25_rank"] is not None and row["bm25_rank"] <= 50),
        ("knn_support_present", lambda row: row["knn_support"] > 0),
    ])
    return policies


def select_policy(rows: list[dict[str, Any]], name: str, predicate: Callable[[dict[str, Any]], bool]) -> list[dict[str, Any]]:
    if name.startswith("per_query_missing_top_"):
        cap = int(name.rsplit("_", 1)[1])
        per_query: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for row in rows:
            per_query[row["query_id"]].append(row)
        return [row for qid in sorted(per_query) for row in sorted(per_query[qid], key=lambda x: (x["union_rank"], x["doc_id"]))[:cap]]
    return [row for row in rows if predicate(row)]


def sha_rows(rows: list[dict[str, Any]]) -> str:
    digest = hashlib.sha256()
    for row in sorted(rows, key=lambda x: (x["query_id"], x["union_rank"], x["doc_id"])):
        digest.update(f"{row['query_id']}\t{row['doc_id']}\n".encode())
    return digest.hexdigest()


def gold_diagnostics(
    selected: list[dict[str, Any]], baseline: dict[str, dict[str, Any]], existing: dict[str, set[str]],
) -> dict[str, Any]:
    selected_by_qid: dict[str, set[str]] = defaultdict(set)
    ranks: dict[tuple[str, str], int] = {}
    for row in selected:
        selected_by_qid[row["query_id"]].add(row["doc_id"])
        ranks[(row["query_id"], row["doc_id"])] = int(row["union_rank"])
    rescued: list[tuple[str, str, int, int]] = []
    all_gold = total_gold = covered_gold = 0
    k200_miss_gold = k200_miss_covered = 0
    multi_gold = multi_gold_covered = 0
    for qid, base in baseline.items():
        gold = set(map(str, base["gold_documents"]))
        total_gold += len(gold)
        scored = existing[qid] | selected_by_qid[qid]
        covered_gold += len(gold & scored)
        for doc in gold:
            if doc not in existing[qid]:
                k200_miss_gold += 1
                k200_miss_covered += int(doc in scored)
            if len(gold) > 1:
                multi_gold += 1
                multi_gold_covered += int(doc in scored)
        for doc in gold & selected_by_qid[qid] - set(map(str, base["top5"])):
            rescued.append((qid, doc, ranks[(qid, doc)], int(base["fold"])))
    # The requested 120 is the fixed missing-BGE rescue cohort (not all newly selected gold).
    fixed_cohort: list[tuple[str, str, int, int]] = []
    for qid, base in baseline.items():
        # Candidate was absent from all existing scores, but its locked-union rank is known only when selected.
        for doc in set(map(str, base["gold_documents"])) - set(map(str, base["top5"])):
            if doc not in existing[qid]:
                # A full rank map is reconstructed from the all-missing rows through ranks below.
                fixed_cohort.append((qid, doc, -1, int(base["fold"])))
    # Fixed cohort needs exact union membership; resolve it from all policies' parent candidate rows is handled by caller.
    return {
        "candidate_oracle_ceiling_with_existing_plus_policy": covered_gold / total_gold,
        "covered_gold_docs": covered_gold, "total_gold_docs": total_gold,
        "k200_miss_gold_covered": {"covered": k200_miss_covered, "total": k200_miss_gold},
        "multi_gold_docs_covered": {"covered": multi_gold_covered, "total": multi_gold},
        "selected_gold_not_baseline_top5": {"count": len(rescued), "union_rank": distribution([x[2] for x in rescued]), "by_fold": dict(Counter(x[3] for x in rescued))},
        "_unresolved_fixed_cohort": fixed_cohort,
    }


def missing_rescue_diagnostic(selected: list[dict[str, Any]], all_rows: list[dict[str, Any]], baseline: dict[str, dict[str, Any]]) -> dict[str, Any]:
    all_rank = {(row["query_id"], row["doc_id"]): int(row["union_rank"]) for row in all_rows}
    selected_set = {(row["query_id"], row["doc_id"]) for row in selected}
    cohort: list[tuple[str, str, int, int]] = []
    for qid, base in baseline.items():
        for doc in set(map(str, base["gold_documents"])) - set(map(str, base["top5"])):
            key = (qid, doc)
            if key in all_rank:
                cohort.append((qid, doc, all_rank[key], int(base["fold"])))
    kept = [item for item in cohort if (item[0], item[1]) in selected_set]
    dropped = [item for item in cohort if (item[0], item[1]) not in selected_set]
    return {
        "fixed_missing_bge_rescued_gold_cohort": len(cohort),
        "kept": len(kept), "capture_rate": len(kept) / len(cohort) if cohort else None,
        "union_rank_kept": distribution([x[2] for x in kept]),
        "union_rank_dropped": distribution([x[2] for x in dropped]),
        "per_fold": {str(fold): {"kept": sum(x[3] == fold for x in kept), "total": sum(x[3] == fold for x in cohort)} for fold in range(5)},
    }


def evidence_selector_audit(
    baseline: dict[str, dict[str, Any]], k200: dict[str, dict[str, Any]], k500: dict[str, dict[str, Any]],
    lexical: dict[str, dict[str, list[str]]], sample_size: int,
) -> dict[str, Any]:
    train = json.loads((ROOT / "data/raw/btc/LegalIR/train.json").read_text(encoding="utf-8-sig"))

    def audit(cache_name: str, records: dict[str, dict[str, Any]], key: str) -> dict[str, Any]:
        pairs: list[tuple[str, str, list[dict[str, Any]]]] = []
        for qid, record in records.items():
            grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
            for hit in record[key]:
                grouped[str(hit["doc_id"])].append(hit)
            pairs.extend((qid, doc, hits) for doc, hits in grouped.items())
        pairs.sort(key=lambda x: hashlib.sha256(f"{cache_name}:{x[0]}:{x[1]}".encode()).hexdigest())
        pairs = pairs[:sample_size]
        stats = Counter(); source_stats: dict[str, Counter] = defaultdict(Counter)
        for n, (qid, doc, hits) in enumerate(pairs, 1):
            source = CHUNKS / f"{doc}.jsonl"
            if not source.is_file():
                stats["missing_source"] += 1; continue
            chunks = [json.loads(line) for line in source.open(encoding="utf-8") if line.strip()]
            selected = selector_chunks(words(str(train[qid]["question"])), chunks)
            if not selected:
                stats["empty_selected"] += 1; continue
            actual = {str(hit["chunk_id"]) for hit in hits}
            best_actual = sorted(hits, key=lambda h: (-float(h["bge_score"]), int(h.get("dense_rank", 10**9)), str(h["chunk_id"])))[0]
            bucket = "bm25_heavy" if str(doc) in set(lexical["bm25"][qid][:20]) else "dense_heavy"
            target = source_stats[bucket]
            for counter in (stats, target):
                counter["valid"] += 1
                counter["exact_top1"] += int(selected[0] == str(best_actual["chunk_id"]))
                counter["any_overlap_at3"] += int(bool(set(selected[:3]) & actual))
                counter["overlap_count_sum"] += len(set(selected[:3]) & actual)
                counter["jaccard_sum"] += len(set(selected[:3]) & actual) / len(set(selected[:3]) | actual)
        def summarise(counter: Counter) -> dict[str, Any]:
            valid = counter["valid"]
            return {"valid_pairs": valid, "missing_source": counter["missing_source"],
                    "exact_top1_overlap_rate": counter["exact_top1"] / valid if valid else None,
                    "any_overlap_at3_rate": counter["any_overlap_at3"] / valid if valid else None,
                    "mean_overlap_count_at3": counter["overlap_count_sum"] / valid if valid else None,
                    "mean_jaccard_at3": counter["jaccard_sum"] / valid if valid else None}
        print(f"[SELECTOR] {cache_name}: valid={stats['valid']}/{len(pairs)}", flush=True)
        return {"sample_requested": sample_size, "sample_pairs": len(pairs), **summarise(stats), "by_candidate_type": {name: summarise(counter) for name, counter in sorted(source_stats.items())}}

    return {"selector": "token_overlap_topk_v1", "k200": audit("k200", k200, "hits"), "k500_v1": audit("k500_v1", k500, "new_hits")}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=RECOVERY / "v2b_slim_preflight")
    parser.add_argument("--selector-sample-per-cache", type=int, default=5000)
    parser.add_argument("--reuse-evidence-report", action="store_true", help="reuse completed evidence audit in report.json; no chunk scan")
    args = parser.parse_args()
    if args.selector_sample_per_cache < 1000:
        raise ValueError("selector sample must be at least 1000")
    baseline, decisions, k200, k500, lexical = load_rankings()
    print("[START] rebuilding locked inference-only union frontier", flush=True)
    all_rows, existing = build_candidates(baseline, decisions, k200, k500, lexical)
    counts = checkpoint_chunk_counts()
    if any((row["query_id"], row["doc_id"]) not in counts for row in all_rows):
        raise ValueError("preflight checkpoint coverage does not match missing candidate pool")
    frontier: dict[str, Any] = {}
    selections: dict[str, list[dict[str, Any]]] = {}
    for name, predicate in policy_definitions():
        selected = select_policy(all_rows, name, predicate)
        selections[name] = selected
        docs_per_query = Counter(row["query_id"] for row in selected)
        chunks = sum(counts[(row["query_id"], row["doc_id"])] for row in selected)
        diagnostic = missing_rescue_diagnostic(selected, all_rows, baseline)
        ceiling = gold_diagnostics(selected, baseline, existing)
        ceiling.pop("_unresolved_fixed_cohort", None)
        frontier[name] = {
            "policy_locked_before_gold": True, "candidate_doc_occurrences": len(selected),
            "unique_docs": len({row["doc_id"] for row in selected}), "docs_per_query": distribution(list(docs_per_query.values()) + [0] * (len(baseline) - len(docs_per_query))),
            "chunks_to_score_max_chunks_per_doc_1": len(selected),
            "chunks_to_score_max_chunks_per_doc_2": sum(min(2, counts[(r["query_id"], r["doc_id"])]) for r in selected),
            "chunks_to_score_max_chunks_per_doc_3": chunks,
            "relative_cost_vs_k500_v1_at_3": chunks / K500_COST,
            "reuse_existing_bge_doc_occurrences": 491_335, "new_missing_bge_doc_occurrences": len(selected),
            "worklist_sha256_query_doc": sha_rows(selected), "missing_bge_rescued_gold_diagnostic": diagnostic,
            "candidate_oracle_diagnostic": ceiling,
        }
        print(f"[FRONTIER] {name}: docs={len(selected)} chunks={chunks}", flush=True)
    existing_report = args.output_dir / "report.json"
    if args.reuse_evidence_report:
        if not existing_report.is_file():
            raise FileNotFoundError("--reuse-evidence-report requires an existing report.json")
        evidence = json.loads(existing_report.read_text(encoding="utf-8"))["evidence_selector_sanity"]
        print("[SELECTOR] reusing completed deterministic audit from report.json", flush=True)
    else:
        evidence = evidence_selector_audit(baseline, k200, k500, lexical, args.selector_sample_per_cache)
    # Fixed, inference-only choice: the deepest union-rank frontier that remains
    # below the 1.0x K500 V1 cost budget.  This is decided from cost and locked
    # inference rank only, before consulting the diagnostic labels above.
    chosen_name = "union_rank_le_50"
    chosen = frontier[chosen_name]
    selector_ok = min(evidence["k200"]["any_overlap_at3_rate"] or 0, evidence["k500_v1"]["any_overlap_at3_rate"] or 0) >= 0.20
    cost_ok = chosen["relative_cost_vs_k500_v1_at_3"] <= 1.5
    status = "V2B_SLIM_READY_FOR_GPU" if selector_ok and cost_ok else ("EVIDENCE_SELECTOR_MISMATCH_BLOCKS_GPU" if not selector_ok else "V2B_SLIM_NOT_WORTH_GPU")
    plan = {"policy_name": chosen_name, "selection_basis": "fixed union-rank cap=50; deepest hand-specified rank frontier under 1.0x K500 V1 cost, independent of gold",
            **chosen, "evidence_selector": "token_overlap_topk_v1", "expected_output_paths": {"beam_output_dir": "/workspace/p13/runtime/artifacts/task1/recovery_096/selective_bge_bounded_union_v2b_slim", "local_download_dir": "artifacts/task1/recovery_096/selective_bge_bounded_union_v2b_slim_from_beam"}}
    report = {"schema_version": "v2b-slim-preflight-v1", "status": status,
              "constraints": {"no_gpu_scoring": True, "no_neural_training": True, "no_submission": True, "gold_used_only_after_policy_lock": True},
              "locked_union": "RRF rank-only/equal weights/rrf_k=60, adaptive+BM25+KNN word+KNN char, cap=200",
              "full_preflight_reference": json.loads((RECOVERY / "selective_bge_bounded_union_v2b_preflight/report.json").read_text(encoding="utf-8")),
              "frontier": frontier, "evidence_selector_sanity": evidence, "recommended_plan": plan,
              "decision_rule": {"selector_any_overlap_at3_minimum": 0.20, "cost_maximum_relative_to_k500_v1": 1.5}}
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = ["# V2B Slim preflight", "", f"Status: `{status}`", "", "| Policy | docs | chunks@3 | cost vs K500 | rescued-gold capture |", "|---|---:|---:|---:|---:|"]
    for name, value in frontier.items():
        diag = value["missing_bge_rescued_gold_diagnostic"]
        lines.append(f"| {name} | {value['candidate_doc_occurrences']:,} | {value['chunks_to_score_max_chunks_per_doc_3']:,} | {value['relative_cost_vs_k500_v1_at_3']:.3f}x | {diag['kept']}/{diag['fixed_missing_bge_rescued_gold_cohort']} ({diag['capture_rate']:.3f}) |")
    lines.extend(["", "## Selector sanity", "", json.dumps(evidence, ensure_ascii=False, indent=2), ""])
    (args.output_dir / "report.md").write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"status": status, "output_dir": str(args.output_dir), "recommended_policy": chosen_name,
                      "recommended_chunks": chosen["chunks_to_score_max_chunks_per_doc_3"], "recommended_cost": chosen["relative_cost_vs_k500_v1_at_3"],
                      "selector_any_overlap_at3": {name: evidence[name]["any_overlap_at3_rate"] for name in ("k200", "k500_v1")}}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
