"""Reproducible raw-to-processed orchestration for legal-document ingestion."""

from pathlib import Path
from typing import List, Union

from pydantic import BaseModel, Field

from udsc2026.ingestion.chunking import ValidationReport, write_chunking_outputs
from udsc2026.ingestion.cleaners import clean_raw_documents
from udsc2026.ingestion.readers import extract_raw_documents


class IngestionPipelineResult(BaseModel):
    """Counts and audit locations generated by one complete ingestion run."""

    raw_document_count: int
    cleaned_document_count: int
    chunked_document_count: int
    document_ids: List[str] = Field(default_factory=list)
    validation_report: ValidationReport
    processed_root: str


def run_ingestion_pipeline(
    raw_directory: Union[str, Path] = "data/raw/btc",
    processed_root: Union[str, Path] = "data/processed",
    chunk_size: int = 512,
    chunk_overlap: int = 80,
) -> IngestionPipelineResult:
    """Run extract, clean, structure-aware chunking, and validation in order.

    The function is deliberately deterministic: the reader sorts source files,
    every stage writes to a fixed directory below ``processed_root``, and any
    document-level extraction or cleaning failure is recorded in metadata
    rather than aborting the remaining corpus.
    """
    root = Path(processed_root)
    metadata_dir = root / "metadata"
    raw_documents = extract_raw_documents(
        str(raw_directory), str(metadata_dir / "extract_errors.json")
    )
    clean_documents = clean_raw_documents(
        raw_documents,
        output_dir=root / "documents",
        errors_path=metadata_dir / "clean_errors.json",
    )
    chunking_results, report = write_chunking_outputs(
        clean_documents,
        chunks_dir=root / "chunks",
        parents_dir=root / "parents",
        report_path=metadata_dir / "validation_report.json",
        review_path=metadata_dir / "manual_review_documents.json",
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
    )
    return IngestionPipelineResult(
        raw_document_count=len(raw_documents),
        cleaned_document_count=len(clean_documents),
        chunked_document_count=sum(bool(result.chunks) for result in chunking_results),
        document_ids=[document.doc_id for document in clean_documents],
        validation_report=report,
        processed_root=str(root),
    )
